-- PERSON TABLE
insert into PERSON (uid, name, last_name, email, address, phone) values ('a894466c-02de-4f93-adf8-40ecc055b0d1', 'Leoine', 'McGarrell', 'lmcgarrell0@vinaora.com', 'PO Box 97062', '999-494-2303');
insert into PERSON (uid, name, last_name, email, address, phone) values ('adad0201-bb87-4362-80f9-bdc5d0d69f01', 'Isadora', 'Matzl', 'imatzl1@free.fr', 'Room 138', '136-776-1599');
insert into PERSON (uid, name, last_name, email, address, phone) values ('f84c9b77-8f47-41d6-a7af-ef5f0d97fd8c', 'Georgie', 'Climpson', 'gclimpson2@reddit.com', 'PO Box 11576', '128-742-3476');
insert into PERSON (uid, name, last_name, email, address, phone) values ('3970d4b2-1140-469e-8f56-e89e97a3e313', 'Benedetta', 'MacScherie', 'bmacscherie3@whitehouse.gov', 'Apt 256', '532-335-9112');
insert into PERSON (uid, name, last_name, email, address, phone) values ('e855f243-f223-406f-b4ea-c516c81bc577', 'Wilt', 'McCarry', 'wmccarry4@fema.gov', '15th Floor', '620-994-6895');
insert into PERSON (uid, name, last_name, email, address, phone) values ('70450a8c-4ca9-4eb8-b6db-f3a59a21cd10', 'Robby', 'Ubsdale', 'rubsdale5@ifeng.com', 'PO Box 58213', '544-903-6196');
insert into PERSON (uid, name, last_name, email, address, phone) values ('798acec4-af24-4148-b9d5-494c126910de', 'Anatola', 'Northridge', 'anorthridge6@wikipedia.org', 'PO Box 21920', '998-669-8677');
insert into PERSON (uid, name, last_name, email, address, phone) values ('6c25d76b-c459-4cca-850e-d62a203212fa', 'Codi', 'Matyas', 'cmatyas7@godaddy.com', 'Room 809', '321-622-4282');
insert into PERSON (uid, name, last_name, email, address, phone) values ('53573686-b141-474a-82b1-452baa3c8ecd', 'Berty', 'Cowser', 'bcowser8@webs.com', 'PO Box 86541', '325-275-6642');
insert into PERSON (uid, name, last_name, email, address, phone) values ('e93d34fa-f895-477a-9b93-5fd82f542e1d', 'Kylila', 'Fehely', 'kfehely9@bigcartel.com', '11th Floor', '380-272-1416');
insert into PERSON (uid, name, last_name, email, address, phone) values ('1c1611b4-d8ab-469b-babf-27e66b52b8c3', 'Ammamaria', 'Scholig', 'ascholiga@sbwire.com', '4th Floor', '291-131-2611');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9a9f95dc-dfc0-4670-ab3c-3a34d4c0e195', 'Lissa', 'Beldum', 'lbeldumb@latimes.com', 'Suite 40', '527-984-0216');
insert into PERSON (uid, name, last_name, email, address, phone) values ('def73d68-c3f4-4487-928a-9b60a75890e9', 'Shawn', 'Deely', 'sdeelyc@wordpress.com', 'PO Box 17824', '530-581-1318');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9d424632-fba6-44d7-9c97-197268813b63', 'Erin', 'Marlen', 'emarlend@acquirethisname.com', 'Suite 86', '535-403-1475');
insert into PERSON (uid, name, last_name, email, address, phone) values ('034b4897-f6dd-4f6f-9ba0-522eab40a725', 'Dante', 'Paskell', 'dpaskelle@infoseek.co.jp', '14th Floor', '835-882-9318');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c3442f4d-2c9d-4e64-b6da-672e7d6b0e4a', 'Kit', 'Blaisdell', 'kblaisdellf@liveinternet.ru', 'PO Box 87120', '413-412-3589');
insert into PERSON (uid, name, last_name, email, address, phone) values ('caada904-fac6-49e3-ae94-35063b4818e9', 'Maegan', 'Leys', 'mleysg@cam.ac.uk', 'PO Box 4528', '699-638-3478');
insert into PERSON (uid, name, last_name, email, address, phone) values ('260b26ee-c869-4301-a195-71bab06cb8d1', 'Normie', 'Tilliard', 'ntilliardh@gnu.org', 'Suite 74', '158-842-1604');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d21d48e5-5df8-4d0a-ac20-ff504fc54a6e', 'Carmita', 'Merrison', 'cmerrisoni@virginia.edu', 'Room 1090', '989-308-0935');
insert into PERSON (uid, name, last_name, email, address, phone) values ('ba1c7a8c-afc7-4e18-9af0-b5cce5265728', 'Chiquia', 'Gilyott', 'cgilyottj@google.es', 'PO Box 64898', '822-593-6358');
insert into PERSON (uid, name, last_name, email, address, phone) values ('2a438201-dba2-44fb-8f2a-929c08b5ab6a', 'Minne', 'Darnody', 'mdarnodyk@jimdo.com', 'Room 39', '156-882-1503');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9fd498ca-7d52-4caa-a93a-bd5c6cd33b88', 'Bernardo', 'Peddar', 'bpeddarl@alexa.com', 'Suite 96', '235-522-0070');
insert into PERSON (uid, name, last_name, email, address, phone) values ('accc9b0c-7984-4a4b-a070-dc0cc5d471ec', 'Ellis', 'Pibsworth', 'epibsworthm@cbslocal.com', 'PO Box 34656', '899-190-9440');
insert into PERSON (uid, name, last_name, email, address, phone) values ('ea9a1bf7-d0a4-44e7-a71f-77a7de0d63c3', 'Berkeley', 'Gelland', 'bgellandn@arstechnica.com', 'Room 726', '141-310-6228');
insert into PERSON (uid, name, last_name, email, address, phone) values ('462ca38d-1a3b-416b-878f-0a78c9bc09e5', 'Allsun', 'Suermeier', 'asuermeiero@amazonaws.com', 'Room 1532', '356-965-4432');
insert into PERSON (uid, name, last_name, email, address, phone) values ('b7dfd6d7-e795-4e14-b7e1-08b1f8557850', 'Suzie', 'Kiffin', 'skiffinp@histats.com', 'Apt 1115', '117-560-2871');
insert into PERSON (uid, name, last_name, email, address, phone) values ('ae602d08-9ade-41f7-b507-3486b7740501', 'Fin', 'Autie', 'fautieq@yellowbook.com', 'Suite 95', '179-756-4037');
insert into PERSON (uid, name, last_name, email, address, phone) values ('46a0f41c-47b5-444f-92d1-2769e93f5813', 'Emili', 'Vedeneev', 'evedeneevr@deliciousdays.com', 'Apt 1721', '774-574-6529');
insert into PERSON (uid, name, last_name, email, address, phone) values ('8f344455-88b6-489a-bc1d-148b833c94e8', 'Francklyn', 'Danbi', 'fdanbis@sciencedaily.com', 'PO Box 35516', '784-815-0117');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d4bec861-8ada-447c-b4db-f7ae7e394de4', 'Irene', 'Bambrough', 'ibambrought@tumblr.com', '5th Floor', '363-539-7251');
insert into PERSON (uid, name, last_name, email, address, phone) values ('f95d2e43-ea79-4f31-bdde-832011bd0a80', 'Lionello', 'Trenholm', 'ltrenholmu@e-recht24.de', 'Apt 252', '859-924-3023');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d266e832-049e-4fa0-9c10-a96afdc95185', 'Vittorio', 'Reeves', 'vreevesv@amazonaws.com', 'Room 1314', '488-473-1542');
insert into PERSON (uid, name, last_name, email, address, phone) values ('b9e2de75-0163-41dc-a620-25795c17b558', 'Elnora', 'Batchley', 'ebatchleyw@netvibes.com', 'Room 921', '448-294-2553');
insert into PERSON (uid, name, last_name, email, address, phone) values ('3b9a827d-13d0-4de0-ab8e-4ec561d425d6', 'Corry', 'Johncey', 'cjohnceyx@slideshare.net', '10th Floor', '492-597-4029');
insert into PERSON (uid, name, last_name, email, address, phone) values ('6ed4bcf5-b903-44fa-abb6-c7dd8ea3a6c0', 'Georges', 'Lake', 'glakey@paginegialle.it', 'PO Box 10813', '433-141-9562');
insert into PERSON (uid, name, last_name, email, address, phone) values ('7584fb8b-4951-45a0-865d-ca3f5f9d1958', 'Nanice', 'Blaisdell', 'nblaisdellz@slashdot.org', 'Suite 21', '377-428-3836');
insert into PERSON (uid, name, last_name, email, address, phone) values ('a6830425-26d8-454e-86c3-66ddc616e9ef', 'Lorene', 'Andrivel', 'landrivel10@cornell.edu', 'PO Box 91353', '758-896-1144');
insert into PERSON (uid, name, last_name, email, address, phone) values ('54013bad-8f11-4877-aabe-320f8c30f709', 'Idaline', 'Addlestone', 'iaddlestone11@phpbb.com', 'Apt 1347', '907-899-2769');
insert into PERSON (uid, name, last_name, email, address, phone) values ('7bd7b833-7656-45ec-92d9-2939d3f78af6', 'Hugh', 'Pryn', 'hpryn12@is.gd', 'PO Box 24491', '402-330-6842');
insert into PERSON (uid, name, last_name, email, address, phone) values ('1fefa493-e064-4186-9330-4c5d5805f432', 'Shae', 'Kahn', 'skahn13@techcrunch.com', 'Apt 732', '830-609-1373');
insert into PERSON (uid, name, last_name, email, address, phone) values ('72f0ca05-b3f1-4543-ba2d-1ab9674ebc09', 'Sonya', 'Baynon', 'sbaynon14@ucoz.com', '12th Floor', '837-291-9990');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c6b4fd6c-8830-4664-ac00-27585d5f33ce', 'Olympe', 'Shreeves', 'oshreeves15@ca.gov', '10th Floor', '703-312-1607');
insert into PERSON (uid, name, last_name, email, address, phone) values ('554eb7a0-be49-4e65-a334-4f8e76e4f524', 'Ermengarde', 'Spragg', 'espragg16@indiegogo.com', 'Suite 24', '611-492-3121');
insert into PERSON (uid, name, last_name, email, address, phone) values ('fcfc8bcf-f4a2-4a98-9103-5b98aa967525', 'Stephani', 'Dimitriev', 'sdimitriev17@berkeley.edu', '10th Floor', '273-819-7512');
insert into PERSON (uid, name, last_name, email, address, phone) values ('2b897db4-99f8-4942-b8dd-f4c039ef78dc', 'Grata', 'Warburton', 'gwarburton18@hugedomains.com', 'Room 8', '754-914-1601');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d394ff90-0966-482f-bab1-dfaebdbe1d40', 'Conway', 'Shellcross', 'cshellcross19@blogs.com', 'Room 1244', '776-305-0201');
insert into PERSON (uid, name, last_name, email, address, phone) values ('8b130658-d1b8-425c-a661-0b70ec659bdb', 'Bennett', 'Rice', 'brice1a@google.es', 'PO Box 30337', '700-635-3897');
insert into PERSON (uid, name, last_name, email, address, phone) values ('e0f46074-5641-4152-acaf-6aec29286f6d', 'Kailey', 'Wethers', 'kwethers1b@eepurl.com', 'Room 1779', '652-549-8903');
insert into PERSON (uid, name, last_name, email, address, phone) values ('3b2db392-6441-46a4-a818-66b520bc9079', 'Aurilia', 'Reddecliffe', 'areddecliffe1c@trellian.com', 'Apt 1227', '979-702-0050');
insert into PERSON (uid, name, last_name, email, address, phone) values ('77089948-3cfe-4250-8f4d-70a2de66bed4', 'Crawford', 'Origin', 'corigin1d@multiply.com', 'Room 1616', '875-490-7890');
insert into PERSON (uid, name, last_name, email, address, phone) values ('f6bdaf5d-390f-429a-a4fe-cb31a1ad4ad1', 'Danielle', 'Huby', 'dhuby1e@businesswire.com', 'Room 865', '629-171-2405');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d0f703dd-8670-48f7-bf7f-cdcda04926fa', 'Nicolai', 'Richings', 'nrichings1f@feedburner.com', 'Room 1886', '466-299-1148');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c72320b2-61d0-44a5-b1b3-069cce4eb356', 'Guido', 'Monkhouse', 'gmonkhouse1g@goo.gl', 'Room 514', '575-873-0407');
insert into PERSON (uid, name, last_name, email, address, phone) values ('efd21147-3589-47ba-89f5-dffbc7c02e3e', 'Keelia', 'Stonhewer', 'kstonhewer1h@google.de', '7th Floor', '206-959-2616');
insert into PERSON (uid, name, last_name, email, address, phone) values ('7cb3b487-b179-4577-bbb0-6fe98a5f2c62', 'Eda', 'Tottle', 'etottle1i@earthlink.net', 'Suite 100', '284-811-3762');
insert into PERSON (uid, name, last_name, email, address, phone) values ('2dfea993-f5cd-45c8-9327-c42a0adb5bf9', 'Bunnie', 'Halle', 'bhalle1j@4shared.com', 'Suite 76', '127-578-0852');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9440696b-655c-4e8f-9ed3-406b0991216a', 'Romola', 'Ranner', 'rranner1k@apache.org', 'Apt 1436', '263-271-6921');
insert into PERSON (uid, name, last_name, email, address, phone) values ('fa64f03c-dcf4-460e-9c82-352a4f2b711e', 'Ilaire', 'Clemence', 'iclemence1l@shop-pro.jp', 'Room 875', '742-878-5152');
insert into PERSON (uid, name, last_name, email, address, phone) values ('5c0af360-a9db-4c7e-a94a-ff52f6c649d7', 'Becky', 'Shapiro', 'bshapiro1m@baidu.com', 'PO Box 97019', '880-184-8218');
insert into PERSON (uid, name, last_name, email, address, phone) values ('f72f4b28-076f-47a8-a6ef-da6a74d63a7a', 'Julio', 'Cino', 'jcino1n@phpbb.com', '7th Floor', '902-249-7880');
insert into PERSON (uid, name, last_name, email, address, phone) values ('8acf8a8f-c20e-4eff-92d6-ea7b54d23d9a', 'Lock', 'Darragon', 'ldarragon1o@com.com', 'Suite 71', '233-996-7388');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c97e77e2-97ea-4dd5-ac4d-2f529fe41dcc', 'Elonore', 'Langridge', 'elangridge1p@desdev.cn', 'Apt 264', '574-302-8667');
insert into PERSON (uid, name, last_name, email, address, phone) values ('b15b978e-34f8-4664-a3ae-7534f1976abe', 'Dahlia', 'Cauderlie', 'dcauderlie1q@zdnet.com', 'Room 1194', '924-641-4896');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9b450bed-8e10-45ba-8d9a-1e84c51e4fde', 'Daisi', 'Kassidy', 'dkassidy1r@omniture.com', 'Apt 285', '238-708-1407');
insert into PERSON (uid, name, last_name, email, address, phone) values ('2d6e5bfb-550d-4cbd-bac4-4c5cc91766bb', 'Thorpe', 'Duling', 'tduling1s@vimeo.com', 'Apt 1882', '132-986-3231');
insert into PERSON (uid, name, last_name, email, address, phone) values ('f4a97da7-563d-4aea-b47c-ab89b1630c9e', 'Blisse', 'Grim', 'bgrim1t@discuz.net', '4th Floor', '607-228-0338');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d0ce167e-2f94-4d92-9b19-b0bf9847e6d6', 'Alex', 'Sharples', 'asharples1u@patch.com', 'Suite 66', '290-317-9808');
insert into PERSON (uid, name, last_name, email, address, phone) values ('e241ad7b-b5a9-4d03-b4a8-73e1c6ab10ce', 'Carree', 'Joerning', 'cjoerning1v@chicagotribune.com', 'PO Box 99607', '186-653-2239');
insert into PERSON (uid, name, last_name, email, address, phone) values ('b1cf8711-667d-4e0d-9482-cacccf5bfbaa', 'Hedvig', 'Weth', 'hweth1w@multiply.com', 'Room 216', '943-105-2349');
insert into PERSON (uid, name, last_name, email, address, phone) values ('b529c6d1-c327-465b-bfef-345c30b1ad13', 'Kordula', 'Mordue', 'kmordue1x@usgs.gov', '7th Floor', '596-682-6687');
insert into PERSON (uid, name, last_name, email, address, phone) values ('8507fd9f-cf28-4223-a180-ccf0275fe968', 'Vinnie', 'Dottrell', 'vdottrell1y@illinois.edu', '15th Floor', '523-543-7699');
insert into PERSON (uid, name, last_name, email, address, phone) values ('91571f3a-c6ff-4f4b-b208-a96b05899cd3', 'Hashim', 'Hollibone', 'hhollibone1z@blinklist.com', 'Suite 14', '987-844-0626');
insert into PERSON (uid, name, last_name, email, address, phone) values ('5a696e4f-eb7e-47aa-a508-c0a3a0453858', 'Bili', 'Tripe', 'btripe20@de.vu', 'PO Box 50237', '768-389-2016');
insert into PERSON (uid, name, last_name, email, address, phone) values ('53aff3c5-d2d1-4ebf-8f35-33623e13ff7b', 'Hope', 'Traves', 'htraves21@bloglines.com', 'PO Box 13239', '136-679-2772');
insert into PERSON (uid, name, last_name, email, address, phone) values ('863dda13-f8dd-43ba-adcd-9bb4b9e7c219', 'Corey', 'Cosham', 'ccosham22@sun.com', '7th Floor', '600-351-4764');
insert into PERSON (uid, name, last_name, email, address, phone) values ('9359ca32-9550-49f8-a405-ffbeb49ae39d', 'Zulema', 'Gres', 'zgres23@engadget.com', 'Apt 772', '962-206-7613');
insert into PERSON (uid, name, last_name, email, address, phone) values ('86ce90e5-118e-49db-b0ff-155d8f164355', 'Cale', 'Stearne', 'cstearne24@phpbb.com', '2nd Floor', '339-903-4688');
insert into PERSON (uid, name, last_name, email, address, phone) values ('6cad29bd-31d0-48a4-a0a2-7bfccf0d2852', 'Derrick', 'Frushard', 'dfrushard25@jimdo.com', '8th Floor', '664-866-5459');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d07260f2-8c10-47bf-a297-11b5cee288bd', 'Maudie', 'Askwith', 'maskwith26@angelfire.com', 'Suite 83', '745-458-5706');
insert into PERSON (uid, name, last_name, email, address, phone) values ('7823ad0d-184b-4ab8-bec4-e665cb07f8ca', 'Reagan', 'McArthur', 'rmcarthur27@123-reg.co.uk', 'Apt 1688', '253-557-4222');
insert into PERSON (uid, name, last_name, email, address, phone) values ('23958bfd-79e1-4876-8905-732c2ec0416c', 'Christie', 'Bessant', 'cbessant28@imageshack.us', 'Room 541', '663-686-9879');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c0ba624f-02bb-4537-844c-bc955bef6213', 'Willi', 'McNelis', 'wmcnelis29@mapy.cz', 'Room 1237', '302-890-9277');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d6534627-f8fb-4e75-ac18-500191360f9a', 'Reena', 'Brixey', 'rbrixey2a@bing.com', 'PO Box 16197', '963-956-1876');
insert into PERSON (uid, name, last_name, email, address, phone) values ('74a82acf-1674-427f-92b7-9fa34496a024', 'Augustine', 'Fraczak', 'afraczak2b@hhs.gov', '14th Floor', '993-278-6699');
insert into PERSON (uid, name, last_name, email, address, phone) values ('fa737c89-72a4-447e-ac90-30d00c3c0752', 'Elladine', 'Postlethwaite', 'epostlethwaite2c@uol.com.br', '3rd Floor', '737-537-4520');
insert into PERSON (uid, name, last_name, email, address, phone) values ('baa77dc9-268e-4bfd-b535-76c3bdfc03f4', 'Freddie', 'Awmack', 'fawmack2d@thetimes.co.uk', '15th Floor', '896-917-6726');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c5ee6ae1-8653-4dfb-987c-5051217c98fa', 'Jacinthe', 'Blanshard', 'jblanshard2e@bing.com', 'Apt 857', '257-801-1572');
insert into PERSON (uid, name, last_name, email, address, phone) values ('e598fa62-ce84-476d-8c35-283efd725c83', 'Riane', 'Ironside', 'rironside2f@people.com.cn', 'Apt 1633', '747-700-1537');
insert into PERSON (uid, name, last_name, email, address, phone) values ('a4c76fab-c7e4-48a3-8f43-60b958d9485d', 'Rhea', 'Prozescky', 'rprozescky2g@umn.edu', 'PO Box 74620', '810-266-3139');
insert into PERSON (uid, name, last_name, email, address, phone) values ('6e80cd86-7ec7-44ab-9899-b09e8f51f033', 'Sharlene', 'Phonix', 'sphonix2h@elpais.com', 'Suite 12', '310-445-6142');
insert into PERSON (uid, name, last_name, email, address, phone) values ('c2425ba1-1846-45b3-93a2-cccfdfb11df3', 'Darryl', 'Ramsbotham', 'dramsbotham2i@japanpost.jp', 'Room 285', '484-752-3798');
insert into PERSON (uid, name, last_name, email, address, phone) values ('46666a49-6d8c-49de-b4a7-c93311e57669', 'Poul', 'Carrington', 'pcarrington2j@noaa.gov', 'Apt 1362', '701-221-1325');
insert into PERSON (uid, name, last_name, email, address, phone) values ('fa853135-bfcf-462d-abad-1936bc075f02', 'Jeffie', 'Tweddell', 'jtweddell2k@twitpic.com', 'Suite 39', '920-808-4579');
insert into PERSON (uid, name, last_name, email, address, phone) values ('714d3002-61c8-48d6-bb1a-3490bc1a3c5a', 'Gaylord', 'Angelini', 'gangelini2l@smugmug.com', 'Room 958', '324-881-5729');
insert into PERSON (uid, name, last_name, email, address, phone) values ('1f48f44d-d218-43ff-a29c-0fe5b3d16442', 'Madelon', 'Tunniclisse', 'mtunniclisse2m@list-manage.com', 'Room 157', '393-407-3335');
insert into PERSON (uid, name, last_name, email, address, phone) values ('5b2cea9f-1cd0-499e-8248-724239ff64fe', 'Felike', 'Olkowicz', 'folkowicz2n@huffingtonpost.com', 'PO Box 44289', '263-811-0529');
insert into PERSON (uid, name, last_name, email, address, phone) values ('00ca7bfd-080e-434d-8fe1-23f5e4d6962a', 'Janenna', 'Jacqueme', 'jjacqueme2o@canalblog.com', 'PO Box 5745', '273-955-6116');
insert into PERSON (uid, name, last_name, email, address, phone) values ('d211ae67-684a-4467-b5bd-d06a6d60c58c', 'Maia', 'Crum', 'mcrum2p@bluehost.com', 'Room 1954', '786-395-0017');
insert into PERSON (uid, name, last_name, email, address, phone) values ('07d57422-7136-4fa1-84fb-7762f60d831e', 'Reyna', 'Drillingcourt', 'rdrillingcourt2q@loc.gov', 'Room 1923', '757-248-1410');
insert into PERSON (uid, name, last_name, email, address, phone) values ('79d0e4a0-a04f-4ecd-b0fa-350f45dd188c', 'Tallie', 'Guiel', 'tguiel2r@skype.com', 'PO Box 85304', '729-150-9931');



-- BOOK INSERTS
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780198825548,'The globalization of world politics. An introduction to international relations','Baylis, Smith & Owens','Acoustic Communication',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789211220421,'Gobernanza y desempeño exportador de los servicios modernos en América Latina y la India','Alvarez, Fernández-Stark y Mulder','Music Technology and the project studio',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788413520070,'Pensamiento crítico latinoamericano sobre desarrollo','Tahina Ojeda Medina y María del Carmen Villarreal Villamar','An introduction to music technology',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Debates sobre Cooperación Internacional para el Desarrollo','Jairo Agudelo Taborda','Spatial Audio',2021,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Teoría y práctica de la Cooperación Internacional para el Desarrollo: Una perspectiva desde México','Esther Ponce Adame, Simone Lucatello y Rafael Velázquez Flores','Audio production and critical listening',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789560108456,'Historia de las Relaciones Internacionales de Chile 1810-2020','Raúl Bernal Meza','Loadbang: programming electronic music in Pure Data',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El tiempo y el espacio en la didáctica de las cs.sociales','Cristofol A. Trepat; Pilar Comes','Tratado de los objetos musicales',2006,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9507013806,'La transposición didáctica : del saber sabio al saber enseñado','Chevallard, Yves y otros','Sound Design',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Arquitectura limpia: Guía para especialistas en la estructura y el diseño de software','Robert Martin','Tratado de armonia',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Orga','Gene kim','Armonía',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8441532109,'Código limpio','Robert Martin','Armonía del siglo XX',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780134757599,'Refactoring','Martin Fowler','Musica, sociedad y educación',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Renovar el asombro. Un panorama de la poesía infantil y juvenil contemporánea en español','Adolfo Córdova','El ruido eterno: escuchar al siglo XX a través de su música',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'LA NUEVA EDUCACION','Cesar Bona','Ways of Sensing. Understanding the Senses In Society',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Remote Sensing Applications in Environmental and Earth System Sciences','Nicolas R. Dalezios','Libro de los pasajes',2021,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Finanzas corporativas','Ross, Stephen A., Westerfield, Randolph W., Jaffé, Jeffrey F., Jordan, Bradford D.','Breve historia de la fotografía',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Física universitaria. Vol 1. Décimo primera edición','Sears, Francis W., Zemansky, Mark W., Young','Calle de sentido unico',2004,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Farmacología para Enfermeras','Rodrígez Palomares C., Garfias Arvizu, A.','3rd Symposium on Potato Cyst Nematodes',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Farmacología en Enfermería. Teoría y Casos Clínicos','Somoza,Beatriz-Cano M. Victoria -López Pedro','La viena de fin de siglo',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786074488562,'Manual de Publicaciones de la American Psychological Association, 4 ª edición ( 7 ª edición en inglé','american psychological association','Terror y utopia',2021,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789561419247,'CHILE 1810-2010. La República en cifras','Gert Wagner - José Díaz - Rolf Lüders','El color del rio',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780128152775,'The Science of Animal Growth and Meat Technology','Steve Lonergan, David Topel, Dennis Marple','en el espacio leemos el tiempo',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Beef Production and Management Decisions (Whats New in Trades & Technology)','Thomas Field','Historia del teatro en Chile (1941-1990)',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071514387,'Micología medica básica','Alexandro Bonifaz','Le Corbusier Redrawn',2020,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789561412606,'La mujer compositora y su aporte al desarrollo musical chileno','Raquel Bustos Valderrama','A Concrete Atlantis',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Earth beings: ecologies of practice across a andean worlds','Marisol de la Cadena','CINCO CARAS DE LA MODERNIDAD: MODERNISMO, VANGUARDIA, DECADENCIA, KITSCH, POSTMODERNISMO',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (97801346027,'Beef Production and management Decisions','Thomas G. Field','Introduction to Ore-Forming Processes',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789561426238,'CHILE 1810-2010. La República en cifras','Gert Wagner, José Díaz, Rolf Lüders','Ore Deposit Geology',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Cerebro y Aprendizaje. Competencias e implicaciones educativas','Jensen, Eric','Eric Fischl: The Krefeld-Project',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Efecto Real. Debates postmodernos sobre fotografía.','Picazo, Gloria y Ribalta, Jorge ed.','Un arte contextual',2004,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789086862924,'INRA feeding system for ruminants','INRA','La Pintura Encarnada',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'La Fotografía. Entre documento y arte contemporáneo','André Rouillé','Teoria de los colores',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Career Paths: Journalism','Charles Moore, Jenny Dooley','Ante la Imagen',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Naturaleza en Sociedad: Una mirada a la dimensión humana de la conservación de la biodiversidad','Cerda, C.; Silva-Rodríguez. E.; Briceño, C.','Lucian Freud Paintings',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780857111746,'Physicochemical Principles of Pharmacy In Manufacture, Formulation and Clinical Use','Florence, Alexander T; Attwood, David','Eric Fischl: The Krefeld-Project',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8499589537,'Tratado general de Biofarmacia y Farmacocinética. Vol. II, Vías de administración de fármacos: aspec','José Doménech Berrozpe','Boltanski',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8499589529,'Tratado general de Biofarmacia y Farmacocinética. Vol. I, LADME, Análisis farmacocinético, Biodispon','José Doménech Berrozpe','El siglo del Collage. Una apreciación radical',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788490222607,'Biofarmacia y farmacocinética: Ejercios y problemas resueltos','Antonio Aguilar Ros, María Consuelo Montejo Rubio, Manuel Caamaño Somoza and Félix Ramón Martín Mart','David Hockeney: El gran Mensaje',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Animal Agriculture: Sustainability, Challenges and Innovations','Fuller W. Bazer, G. Cliff Lamb, Guoyao Wu','Colores, Historia y significado',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781780645070,'Beef Cattle Production Systems','Andy Herring','El color. Un método para dominar el arte de combinar colores',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780134602691,'Beef Production and Management Decisions','Thomas G. Field','Asi lo veo Yo',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781682866566,'Genetic Management of Animals','Dominic Fasso','Diccionario Akal del color',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Nutrient Requirements of Beef Cattle: Eighth Revised Edition (Nutrient Requirements of Animals)','The NationalAcademies of Sciences, Engineering, Medicine','trigonometria',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781682864388,'Animal Breeding and Livestock Management','Carlos Hassey','Clinical Biochemistry of Domestic Animals',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Temple Grandins Guide to Working with Farm Animals: Safe, Humane Livestock Handling Practices for t','Temple Grandin','Veterinary Hematology and Clinical Chemistry,',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8482362836,'Investigación Educativa y experiencia vivida','Max Van Manen','Veterinary Hematology: A Diagnostic Guide and Color Atlas',2003,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8449305659,'El tacto en la enseñanza','Max Van Manen','Canine and Feline Cytology: A Color Atlas and Interpretation Guide',1998,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Nursing','Virginia Evans & Kori Salcido','Exotic Animal Hematology and Cytology',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Technical English for Geosciences','Brigitte Markner-Jäger','Infectious Diseases of the Dog and Cat',2008,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9783319262772,'Global Marketing Strategy. An Executive Digest','Schlegelmilch, Bodo','Atlas of Canine and Feline Peripheral Blood Smears, 1e (Small Animal Laboratory Essentials)',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780134129945,'GLOBAL MARKETING','KEEGAN, WARREN J. - GREEN, MARK C.','Schalms Veterinary Hematology',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'La ciudad de las damas','Cristina de Pizán','Sedimentology and Sedimentary Basins: From Turbulence to Tectonics',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Terapia Ocupacional y pragmatismo: Contribuciones teóricas para la práctica','Rodolfo Morrison Jara','Structural Geology',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Ethnography and Education Policy: A Critical Analysis of Normalcy and Difference in Schools','MATUS CLAUDIA','Atlas para la identificacion de elementos parasitarios microscopicos en deposiciones',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Bovine Reproduction','Richard M. Hopper','Historia de la Música occidental',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Veterinary Reproduction and Obstetrics','David E. Noakes, Timothy J. Parkinson, Gary C. W. England','La interpretación histórica de la música',2019,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Pathways pregnancy & parturition','P.L. Senger','La música en la época Barroca',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'La (de)construcción del conocimiento pedagógico.','Antonio J. Colom Cañellas','Un siglo de música grabada',2002,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Gestionar es hacer que las cosas sucedan','Bernardo Blejmar','Biomimicry Resource Handbook',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El diagnóstico de los niños y adolescentes problemáticos: Una crítica a los discursos sobre los tras','Valerie Harwood','Biophilic Cities: Integrating Nature Into Urban Design and Planning',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El desarrollo del tacto pedagógico','Josep Asensio','JOAO LUIS CARRILHO DA GRACA, TRAZAR CONEXIONES, CONSTRUIR PAUTAS',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Foucault, Power and Education.','Stephen Ball','Constructores Inmigrantes. Transferencia de Alemania a Chile',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'The sociology of education in Canadá. Fifth edition.','Terry Wotherspoon','MVRDV, CIUDAD EVOLUTIVA',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'The Japanese Education System.','Yasuhiro Nemoto','Arquitectura: Crítica y Nueva Época',1999,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Miedo y Osadía. La Cotidianidad del Docente que se Arriesga a Practicar una Pedagogía Transformadora','Freire, P., y Shor, I.','DAVID CHIPPERFIELD, FIGURA Y ABSTRACCIÓN',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'School Trouble. Identity, power and politics in education.','Deborah Youdell','Bevk Perović, CONDICIONALISMO',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'10 años de bilinguismo en Chile','INDESOR y UMCE','SELGASCANO, VACILANTE NATURALEZ',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Lectores sordos bilingues: un logro posible','Herrera Fernandez, Valeria','Arquitectura y Crítica',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781108436694,'TRANSNATIONAL MANAGEMENT: TEXT AND CASES IN CROSS-BORDER MANAGEMENT','CHRISTOPHER BARTLETT - PAUL BEAMISH','Los ojos de la piel. La arquitectura y los sentidos',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'INVESTIGACION DE MARKETING 3.0','TEODORO LUQUE MARTINEZ','ALVARO SIZA, LECCIONES MAGISTRALES',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'TECNICAS DE ANALISIS DE DATOS EN INVESTIGACION DE MERCCADOS','TEODORO LUQUE MARTINEZ','SMILJAN RADIC, EL JUEGO DE LOS OPUESTOS',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'TECNICAS DE ANALISIS DE DATOS EN INVESTIGACION DE MERCCADOS','TEODORO LUQUE MARTINEZ','Glenn Murcutt Feathers Of Metal',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788580552553,'Química General','Chang, Raymond','STEVEN HOLL, CONCEPTOS Y MELODÍAS',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9702612861,'Química General','John E. McMurry','Neutelings Riedijk, CONVENCIONES E IDENTIDAD',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789505577088,'Karl Marx o el espíritu del mundo','Jacques Attali','Arquitectura y Crítica',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Enseñando, afirmando y reconociendo a jóvenes trans*+ y de género creativo: Un marco de enseñanza qu','SJ Miller','Studio Mumbai, MANERAS DE HACER Y DE FABRICAR',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Data Science for Business','Foster Provost and Tom Fawcett','Valerio Olgiati, AFINADAS DISCORDANCIAS',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Big Data Fundamentals: Concepts, Drivers & Techniques','Thomas Erl, Wajid Khattak, and Paul Buhler','SANAA, ARQUITECTURA INORGÁNICA',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'A Beginners Guide to Structural Equation Modeling','Randall E. Schumaker & Richard G. Lomaz','Aires Mateus, CONSTRUIR EL MOLDE DEL ESPACIO',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'A Primer on Partial Least Squares Structural Equation Modeling (PLS-SEM)','Joe Hair, G. Tomas M. Hult, Christian M. Ringle & Marko Sarstedt','Herzog & de Meuron, PROGRAMA, MONUMENTO, PAISAJE',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Business Intelligence Guidebook: From Data Integration to Analytics','Rick Sherman','Sou Fujimoto, TEORÍA E INTUICIÓN, MARCA Y EXPERIENCIA',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El reencantamiento del mundo','Morris Berman','Caruso St John, RUDA SUTILEZA',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788415053668,'Comunicación no violenta un lenguaje de vida','Marshall B. Rosenberg','Sean Godsell, RUDA SUTILEZA',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Explaining Music : Essays and Explorations','Leonard Meyer','RCR Arquitectes, ABSTRACCIÓN POÉTICA',1978,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El Hombre, Un Signo','Charles Sanders Peirce','Mansilla+Tuñón, GEOMETRÍAS ACTIVAS',1988,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Contra la interpretación y otros ensayos','Susan Sontag','ECONOMIA URBANA Y REGIONAL: INTRODUCCION A LA GEOGRAFIA ECONOMICA',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Charles Sanders Peirce: Semiótica, iconicidad y analogía','Mauricio Beuchot','Spatial Behavior: A Geographic Perspective',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'The Musical Representation : Meaning, Ontology, and Emotion','Charles O. Nussbaum','Ecología Forestal: Bases para el manejo sustentable y conservación de los bosques nativos de Chile',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Metafisicas Canibales','Eduardo Viveiros de Castro','Gestion del Cuidado en Enfermeria.',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Semiótica - Textos Selectos','Charles Sanders Peirce','Gestion del Cuidado en Enfermeria.',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Spaces speak, are you listening','Harry Blesser','Aprender a Cuidar. Didactica del Proceso de Enfermeria.',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8494051903,'Gramática árabe comentada','Antonio morales delgado','Aprender a Cuidar. Didactica del Proceso de Enfermeria.',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8493741035,'Gramática práctica de árabe','Joana hernández martínez','Aprender a Cuidar. Didactica del Proceso de Enfermeria.',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781564240354,'Seismic Design Manual, 3rd Edition','AMERICAN INSTITUTE OF STEEL CONSTRUCTION','Aprender a Cuidar. Didactica del Proceso de Enfermeria.',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Steel Construction Manual, 15th Ed.','AMERICAN INSTITUTE OF STEEL CONSTRUCTION','Gestion del Cuidado en Enfermeria.',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071512093,'MARKETING INTERNACIONAL','PHILIP CATEORA','Geomorfología',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788483226407,'Estrategias de Marketing internacional','Svend Hollensen','Atlas para la identificacion de elementos parasitarios microscopicos en deposiciones',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786074819489,'MARKETING INTERNACIONAL','CZINKOTA, MICHAEL','The American Vitruvius: An Architects Handbook of Civic Art',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788483226407,'ESTRATEGIAS DE MARKETING INTERNACIONAL','HOLLENSEN, SVEND','Sitte, Hegemann and the Metropolis: Modern Civic Art and International Exchanges',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071512901,'NEGOCIOS INTERNACIONALES COMO COMPETIR EN EL MERCADO GLOBAL','Charles W. L. Hill','PROYECCIONES RADIOLOGICAS Y CORRELACION ANATOMICA (6ª ED.)',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'MARKETING INTERNACIONAL','PHILIP CATEORA','Techniques for Virtual Palaeontology',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Nickel 1','Hélène Auge Npai','¿Quién le póne el cascabel al gato?',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El Toro de Minos','Leonard Cottrell','DIDACTICA DE LA LIBERACION: ARTE CONCEPTUALISTA LATINOAMERICANO',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Arquitectura y ciudad moderna en el sur de Chile. Memoria, territorio y proyecto','Pablo Fuentes y Veronica Esparza editores','Peter Zumthor: Buildings and Projects, 1985-2013',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (1119142288,'Principles of Genetics','D. Peter Snustad','Arquitectura Contemporánea',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788494100819,'El precariado. Una nueva clase social','Guy Standing','LA ESFERA Y EL LABERINTO, Vanguardia y arquitectura de Piranesi a los años 70',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'DESIGN AND ANALYSIS OF EXPERIMENTS VOLUMEN 1, 2 Y 3','HINKELMANN, KLAUS AND KEMPTTHORNE, OSCAR','Teorías e Historia de la Arquitectura',2008,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'DESIGN AND ANALYSIS OF EXPERIMENTS WITH R','LAWSON, JOHN','Fundamentos de Economía',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Veterinary embryology','MacGeady, Thomas A., Quinn, P. J., FitzPatrick, E. S., Ryan, M. T., Cahalan, S.','Form in tonal music: an introduction to analysis',2006,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Essentials of domestic animal embryology','Hyttel, Poul; Sinowatz, Fred; Vejlsted, Morten','Anthology of Musical Analysis',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Embriología médica','Langman, Jan; Sadler, T. W.','INGENIERIA DE CARRETERAS Vol. II',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (321643755,'Environmental Geology','Edward Keller','Handbook of Marine Craft Hydrodynamics and Motion Control',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Environmental Geology: An Earth Systems Approach','Merritts, D., Menking, K., DeWet, A.','Guidance and Control of Ocean Vehicles',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (73524115,'Environmental Geology','Montgomery, C.','Suelos de Chile',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Conservation and Development','Andrew Newsham, Shonil Bhagwat','"Historia de la música occidental de Carlos Poblete Varas"',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'ADMINISTRACION. UN ENFOQUE BASADO EN COMPETENCIAS','HELLRIEGEL, DON; JACKSON, SUSAN; SLOCUM JR, JOHN','Por una pedagogía de la pregunta',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786073227674,'ADMINISTRACION','ROBBINS, STEPHEN; COULTER, MARY','Corpus',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Auditoría Interna','Juan Ramón Santillana González','Ulises',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Auditoría un enfoque integral','Alvin A. Arens-Randal Elder-Mark Beasley','Geomorfología',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786075197647,'TEORIA Y DISEÑO ORGANIZACIONAL','DAFT, RICHARD L.','Construyendo escuelas democráticas',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786075197647,'TEORIA Y DISEÑO ORGANIZACIONAL','DAFT, RICHARD L.','El legado Pedagógico del siglo XX para la escuela del siglo XXI',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786073221177,'TEORIA ORGANIZACIONAL, DISEÑO Y CAMBIO EN LAS ORGANIZACIONES','JONES, GARETH R.','Aprendizaje dialógico en la Sociedad de la Información',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786073221177,'TEORIA ORGANIZACIONAL, DISEÑO Y CAMBIO EN LAS ORGANIZACIONES','JONES, GARETH R.','Administración y Gestión efectiva en la unidad escolar',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786073227674,'ADMINISTRACION','ROBBINS, STEPHEN; COULTER, MARY','Parasitología humana',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071509802,'INTRODUCCION A LA TEORIA GENERAL DE LA ADMINISTRACION','CHIAVENATO, IDALBERTO','The Anthropology of Self and Behavior',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071509802,'INTRODUCCION A LA TEORIA GENERAL DE LA ADMINISTRACION','CHIAVENATO, IDALBERTO','New Directions in Psychological Anthropology',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Anatomía topográfica y aplicada de los animales domésticos','BERG, Rolf','Prueba',1987,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071513670,'Farmacología Básica y Clínica','Bertram G. Katzung','Prueba',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Hearing by Whales and Dolphins','Richard R. Fay, Whitlow W.L. Au','Micología - Médica Básica',2000,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Comparative Hearing: Mammals','Richard R. Fay','100 ideas que cambiaron la arquitecura',1994,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Aritmética y Álgebra Manual Esencial','Baeza, Ángela y otros','Leer la arquitecura, diccionario visual',2008,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8484766616,'Edafología. Uso y Protección de los Suelos','Jaume Porta, Marta López-Acevedo, Rosa Poch','OBRAS MAESTRAS DE LA ARQUITECTURA MUNDIAL',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780133254556,'Nature and Properties of Soils, The, 15th Edition','Raymond R. Weil, Nyle C. Brady','Bases Científicas de la Drogadicción',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'ENCYCLOPEDIA OF SOILS IN THE ENVIRONMENT FOUR-VOLUME SET','Daniel Hillel (Editor-in-Chief)','Métodos de investigación clínica y epidemiológica',2004,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Álgebra','Oteyza, Elena de','Macroevolution: Diversity, Disparity, Contingency: Essays in Honor of Stephen Jay Gould',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Gray, Anatomía para estudiantes','Richard L Drake; Wayne Vogl; Adam W M Mitchell','Principles of paleontology',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071505835,'Negocios Internacionales. Competencia en el mercado global','Charles Hill','Nelson Tratado de Pediatría',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786074817768,'Negocios Globales','Mike Peng','Invitation to Oceanography',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789563496239,'Números Texto para el formador para futuros profesores de enseñanza básica','Martínez, Salomé y otros','Estuaries: A Physical Introduction',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Matemáticas para maestros de Educación Primaria','Segovia, Isidoro y Rico, Luis','Obstetrics: Normal and Problem Pregnancies:',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789563495980,'Álgebra para futuros profesores de enseñanza básica','Martínez, Salomé y otros','Fetal Monitoring Interpretation',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789569741029,'Arquitectura y ciudad moderna en el sur de Chile. Memoria, territorio y proyecto','Pablo Fuentes y Veronica Esparza editores','cirugía endoscópica en ginecología',2017,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'TRATADO PRÁCTICO DE HORTICULTURA','G. Sasias y C. Chesne, M. Guedj','Doppler en medicina fetal',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Sedimentología: del proceso físico a la cuenca sedimentaria','Alfredo Arches Miralles','GRANDES CALLES',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788472070745,'Estratigrafía: principios y métodos','Juan Antonio Vera Torres','EL CONOCIMIENTO SECRETO',1994,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788439727972,'Como funciona la música','David Byrne','EL CONOCIMIENTO SECRETO',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788483229675,'Introducción a la Econometría, 3ed','Stock, James; Watson, Mark','Finanzas Corporativas',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786070506970,'Química Orgánica','Solomons','Las Finanzas en las Empresas Multinacionales',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071512109,'Química Orgánica','Carey, F.A. McGraw-Hill: México, 2006','Ecological Urbanism',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786070506963,'Química Orgánica','Solomons, T.W.G.','INTRODUCCION AL URBANISMO. LA EVOLUCIÓN DE LAS CIUDADES: LA LECCIÓN DE LA ANTIGÜEDAD',2000,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786077781684,'¿Cómo funcional la música?','David Byrne','chilean modern architecture since 1950',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8461090152,'A La Escucha','Jean-Luc Nancy','Pathologic Basis of Veterinary Disease',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8432209473,'Escucha esto','Alex Ross','Psicologia',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789871622528,'Oceano de sonido','David Toop','Teorías de la Personalidad',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788495818331,'HOTELERIA Y TURISMO: MANUAL DE ADMINISTRACIÓN HOTELERA','VV.AA.','DICCIONARIO DE TERMINOS SOBRE LA CIUDAD Y LO URBANO',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789972209970,'TURISMO, HOTELERÍA Y RESTAURANTES','VV.AA.','Urbanismo Bioclimático',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9786071701985,'COMPETITIVIDAD DE LOS DESTINOS TURÍSTICOS','MIGUEL ANGEL ACERENZA','Pediatría Ambulatoria con Enfoque Integral',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'TURISMO 2.0','TOMAELLO, FLAVIA Y DUER, WALTER','Semiología Pediatrica',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9562389243,'Contabilidad información y control en las empresas; SEXTA EDICIÓN','GABRIEL TORRES SALAZAR','Pediatría Ambulatoria',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Preparación y Evaluación de Proyectos','Nassir Sapag Chain, Reinaldo Sapag Chain, José Manuel Sapag P.','Desarrollo Humano',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780134436050,'Introduction to Animal Science: Global, Biological, Social and Industry Perspectives','W. Stephen Damron','Dimensions of the Sustainable City',2018,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Una guerra infame La verdadera historia de la Conquista del Desierto','Andrés Bonatti , Javier Valdez','la ciudad generica',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Química, la Ciencia Central','Theodore L. Browm','IDEAS QUE HAN CONFIGURADO EDIFCIIOS',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Gaia: una ciencia para curar el planeta','James Lovelock','Espacio Basura',1999,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788484764311,'Las Maquinas Agrícolas Y Su Aplicación','Ortiz-Cañavate Jaime','Arquitectura y politica, ensayos para mundos anternativos',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789870008606,'Metodologías de acción social','Ezequiel Ander Egg','LA ARQUEOLOGIA DEL SABER',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781447923831,'ENGLISH FOR INTERNATIONAL TOURISM COURSEBOOK. INTERMEDIATE.','Peter Strutt','DICCIONARO MANUAL ILUSTRADO DE ARQUITECTURA',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'BASES METODOLÓGICAS PARA EL DIAGNÓSTICO BACTERIOLÓGICO DE LAS INFECCIONES POR CAMPYLOBACTER','Heriberto Fernández J., Sofía Ochoa A., Janneth Simaluiza M.','DIEZ EDIFICIO CANONICOS 1950-2000',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'The Maya Rain Forest Garden, eight milenia of sustanible cultivation of the tropical woodlands','Anabel Ford y Ronald Nigh','SENDAS ONIRICAS DE SINGAPUR, RETRATO DE UNA METROPOLIS POTEMKIM… O TREINTA AÑOS DE TABLA RASA',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (8420007676,'La evaluación sensorial de los alimentos en la teoría y la práctica','Antonio Anzaldúa-Morales','CASA CON PATIO',1994,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788415556114,'Teatro Posdramático','Hans_Thies Lehmann','ARQUITECTURA MODERNA EN ZONAS SISMICAS',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'La Odisea','Homero','SISTENAS ARQUITECTONICOS CONTEMPORANEOS',2006,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'La Ilíada','Homero','ALEGORIA DEL PATRIMONIO',2006,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781455740062,'Georgis´ Parasitology for veterinarians','D Bowman','APRENDIENDO DEL POP',2013,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Equine Surgery','Auer & Stick','APRENDIENDO DEL POP',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Medicina Interna de grandes animales','BP Smith','MEGAESTRUCTURAS, FUTURO URBANO DEL PASADO RECIENTE',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9781416056706,'Equine Internal Medicine','SM Reed, WM Bayly, DC Sellon (editores)','2G LIBROS, LINA BOBARDI, OBRA CONSTRUIDA',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (865778264,'AO Principles of Equine Osteosynthesis','Fackelman, Auer, Nunamaker, Bramlage, Markel, Richardson','Estética de la desaparición',1999,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Atlas of Equine Endoscopy','Natahn Slovis','manifiestos,proclamas y polémicas de la vanguardia literaria hispanoamericana',2004,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Adams & Stashak´s Lameness in horses','Gary Baxter','Después del fin del arte.El arte contemporáneo y el linde de la historia',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Diagnosis and management of lameness in the horse','Roos & Dyson','Handbook of Food Safety Engineering',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788498411034,'EN EL MUNDO INTERIOR DEL CAPITAL. PARA UNA TEORIA FILOSOFICA DELA GLOBALIZACION','PETER SLOTERDIJK','La buena vida, visita guiada a las casas de la modernidad',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788498410648,'EN EL ESPACIO LEEMOS EL TIEMPO','KARL SCHLOGEL','HISTORIA DE LA ARQUTECTURA MEXICANA',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9788446020646,'Espacio del capital. Hacia una geografía critica','David Harvey','HISTORIA CRITICA DE LA ARQUITECTURA MODERNA',2007,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9789681675318,'La nueva naturaleza de los mapas : ensayos sobre la historia de la cartografía','John Brian Harley','Arquitectura latinoamericana contemporanea',2006,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Journal of Paloebiology DOI: http://dx.doi.org/10.1017/pab.2016.6','-autores en revista- solicitud de inscrpción en revista electrónica sin open access','La arquitectura compuesta por partes',2016,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'THE UNITED STATES PHARMACOPEIA - en español (USP 38 NF 33)','United States Pharmacopeia','Lo Ordinario',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Psicología del Desarrollo, de la infancia a la adolescencia','Papalia , Wendkos y Duskin','Pensar la arquitectura',2005,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Metodología de la investigación educativa','Bisquerra, Rafael','Cuestiones de persepcion, Fenomenologia de la arquitectura',2014,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (9780729583442,'Introduction to Public Health: Edition 3','Mary Louise Fleming Elizabeth Parker','La ciudad',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Summa+ 76','Varios autores','LA ARQUITECTURA MODERNA, UNA HISTORIA DESAPASIONADA',2005,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Summa +114','Varios autores','Historia del presente inmediato, la invencion del movimiento moderno arquitectonico',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Summa+ 116','Varios autores','Atmosferas',2012,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Summa+ 126','Varios autores','Vigilar y Castigar',2011,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'El Croquis 144','Varios autores','La arqueologia del saber',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'JA 99','Varios autores','Grandeza, o el problema de la talla',2015,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Detail 3 Concept','Varios autores','Administración de Operaciones. Conceptos y casos contemporáneos',2010,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Acoustics and the Performance of Music','Jurgen Meyer','Color ambiental, aplicaciones en arquitectura',2009,'');
INSERT INTO book (ISBN,name,author,synopsis,publication_year,image) VALUES (0,'Acústica musical y organología','Tirso de Olozabal','The history of the theory of structures: from arch analysis to computational mechanics',2007,'');


-- LEND INSERTS
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (194, 16, '2022-12-26', '2022-02-08', '2022-01-31');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (84, 62, '2022-07-23', '2022-10-30', '2022-10-15');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (89, 91, '2022-03-25', '2022-11-30', '2022-04-12');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (84, 74, '2022-12-30', '2022-05-05', '2022-02-03');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (79, 86, '2022-03-11', '2022-10-26', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (1, 69, '2022-02-07', '2022-09-16', '2022-06-10');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (143, 73, '2022-03-11', '2022-07-23', '2022-03-02');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (48, 49, '2022-06-21', '2022-01-29', '2022-08-22');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (118, 15, '2022-11-05', '2022-06-13', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (8, 7, '2022-12-31', '2022-10-17', '2022-02-25');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (20, 67, '2022-07-02', '2022-10-28', '2022-08-18');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (96, 81, '2022-02-09', '2023-01-11', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (181, 17, '2022-12-13', '2022-07-05', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (55, 62, '2022-02-18', '2022-01-24', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (129, 88, '2022-10-27', '2022-08-15', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (100, 24, '2022-04-21', '2022-10-24', '2022-06-27');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (125, 16, '2022-03-27', '2023-01-15', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (70, 13, '2022-09-09', '2022-12-14', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (149, 91, '2022-02-13', '2022-03-21', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (98, 28, '2022-06-08', '2022-06-11', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (181, 16, '2022-07-23', '2022-12-12', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (109, 88, '2022-02-09', '2022-12-20', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (3, 85, '2022-03-11', '2022-08-25', '2022-09-08');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (6, 80, '2022-02-26', '2022-11-14', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (40, 56, '2023-01-17', '2023-01-15', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (136, 20, '2022-08-03', '2022-12-14', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (47, 96, '2022-11-19', '2022-07-17', '2022-03-23');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (162, 67, '2022-03-28', '2022-07-18', '2022-02-10');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (168, 21, '2022-04-21', '2022-12-21', '2022-05-13');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (83, 39, '2022-02-12', '2022-08-08', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (166, 18, '2022-02-26', '2022-03-28', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (92, 28, '2022-11-08', '2022-02-09', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (10, 16, '2022-02-28', '2022-10-21', '2022-06-01');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (21, 74, '2022-08-21', '2022-09-01', '2022-09-28');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (13, 22, '2022-12-23', '2022-11-26', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (198, 77, '2022-10-25', '2022-05-23', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (61, 96, '2022-10-21', '2022-09-12', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (41, 34, '2022-08-18', '2023-01-10', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (146, 14, '2022-10-14', '2023-01-02', '2022-02-12');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (177, 66, '2022-04-08', '2022-03-24', '2022-07-19');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (185, 3, '2022-05-17', '2022-05-19', '2022-10-29');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (70, 21, '2022-08-05', '2022-04-10', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (194, 4, '2022-05-10', '2022-11-09', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (16, 2, '2022-03-01', '2022-09-15', '2022-03-16');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (84, 42, '2022-11-30', '2022-04-13', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (88, 23, '2022-10-15', '2022-12-08', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (95, 79, '2022-11-19', '2022-07-16', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (104, 84, '2022-11-24', '2022-06-07', null);
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (55, 14, '2022-06-11', '2022-10-19', '2022-06-12');
insert into LEND (book_id, person_id, lend_date, estimated_return_date, real_return_date) values (16, 32, '2022-10-20', '2022-05-16', '2022-07-27');
